### ISSUE TITLE
[Bug] Couldn't delete chapter in "Recents"

### ISSUE THREAD

**Issue by squeakyquack** [Jays2Kings/tachiyomiJ2K#771] opened 2021-04-28 11:30 UTC
### Device information
* Tachiyomi version: 1.0.15
* Android phone & version: Xiaomi Redmi 5 Plus Oreo

## Steps to reproduce
1. Read any mangas/manhwas/manhuas
2. Try to reset and delete the chapter from "Recents"

### Expected behavior
Chapter will reset and deleted

### Actual behavior
Chapter has been reset, but doesn't delete

**Comment by Jays2Kings** [comment] 2021-05-02 18:06
Duplicate of https://github.com/Jays2Kings/tachiyomiJ2K/issues/756

**Closed by Jays2Kings** 2021-05-02 18:06 UTC
Labels: bug
