### ISSUE TITLE
[Feature Request] Add a mass mark as read option for Mangarock migrators.

### ISSUE THREAD

**Issue by rjr619** [Jays2Kings/tachiyomiJ2K#123] opened 2020-02-22 16:41 UTC
### Why/User Benefit/User Problem
With Mangarock shutting down a large influx of users are coming to tachiyomi and importing their favorites with them. However when imported all chapters are marked as unread and manual marking is slow and tedious. Most of us have well over 400 manga and a mass mark as read option would be a god send.

### What/Requirements
The ability to select multiple manga and mark all chapters read with a single button from the library menu much like the mark all as unread feature already included.

### Side Note
I know this has been requested before but I sincerely think this is a much needed feature as more and more users move away from Mangarock with enormous libraries. I feel the current solution of 1 manga at a time is just not enough.

**Comment by joseph619** [comment] 2020-03-06 08:30
Duplicate of #65

**Closed** 2020-03-06 17:46 UTC
Labels: feature
