### ISSUE TITLE
Create a "migrate bookmarks" option on migration

### ISSUE THREAD

**Issue by James-Yuji** [Jays2Kings/tachiyomiJ2K#670] opened 2021-03-12 04:33 UTC
Why/User Benefit/User Problem
(when migrating a manga/manhwa/webtoon there is no option to migrate bookmarks, hence whenever a title is migrated, all bookmarks are deleted)

What/Requirements
(A option in the migrating menu with such feature would help, put it beside the "tracking" "chapters" "categories" as a data to choose to migrate with the title)

**Comment by GreatestFool** [comment] 2021-04-07 12:59
#671 is identical to this, and also one of yours, so this can be deleted or closed so that attention is not split between Issue threads.

**Comment by joseph619** [comment] 2021-04-13 14:34
Duplicate of #151

**Closed** 2021-04-13 16:08 UTC
Labels: feature
