### ISSUE TITLE
UI bug when marking chapter as read, when you have option to remove after read enabled

### ISSUE THREAD

**Issue by CarlosEsco** [Jays2Kings/tachiyomiJ2K#940] opened 2021-07-21 02:21 UTC
- enable remove when marked as read 
- go to a manga with an unread downloaded chapter
- swipe mark as read

download icon does not reset, and stays solid.  If you back out and go back into the manga it shows undownloaded.  So seems to be no callback to after marking as read

**Comment by Jays2Kings** [comment] 2021-07-21 21:44
not a bug, since there is logic to undo a chapter marked as read, it is when the snack bar dismisses that it will actually perform the callback to actually delete the chapter and update ui (which also happens when going back). An alternative would be to show the chapter as if it was undownloaded, but that would be a lie until that snackbar dismisses (and would magically go back to downloaded if a user presses on undo

https://user-images.githubusercontent.com/8617760/126564022-c621ea6d-885a-4b0e-9065-4814a3043bca.mp4

**Comment by CarlosEsco** [comment] 2021-07-21 21:53
https://user-images.githubusercontent.com/2092019/126565098-33929b92-6194-49f4-ac70-3e8f57cb9460.mp4

The problem seems to be then the snack bar doesn't always dismiss

**Comment by Jays2Kings** [comment] 2021-07-21 21:58
> The problem seems to be then the snack bar doesn't always dismiss

Because of the logic of it, it will dismiss on touch down, but only after 2ish seconds pass, because users seem to have slippery hands. It will never dismiss on its own

**Comment by CarlosEsco** [comment] 2021-07-21 22:02
Dismiss on tap of snack?

**Comment by Jays2Kings** [comment] 2021-07-21 22:03
Native is swioe the snackbar to the right to dismiss 🤷

**Closed** 2021-07-21 22:19 UTC
Labels: bug
