### ISSUE TITLE
[Bug] Dark mode broken 

### ISSUE THREAD

**Issue by joseph619** [Jays2Kings/tachiyomiJ2K#42] opened 2020-01-08 11:20 UTC
Reported by user Thu on Discord

### Device information
* Tachiyomi version: 0.9.55
* Android version: 9

## Steps to reproduce
. Be on dark theme
2. Force closed the app
3. Open app
4. Go to catelog
5. Clicked on mangadex
6. Open webview
7. Closed webview

### Expected behavior
Dark theme should be normal 

### Actual behavior
Dark theme is broken.

### Other details
Screenshots below

![Screenshot_20200108-055729_Tachiyomi](https://user-images.githubusercontent.com/34897862/71974008-6b3ecd00-31de-11ea-878a-0946c2e85010.jpg)

![Screenshot_20200108-055745_Tachiyomi](https://user-images.githubusercontent.com/34897862/71974138-b6f17680-31de-11ea-8d12-887543f31550.jpg)

![screenshot_20200108-055802_tac](https://user-images.githubusercontent.com/34897862/71974216-ec965f80-31de-11ea-937c-bb0c1a8684f4.jpg)

**Comment by arkon** [comment] 2020-01-08 12:18
Can confirm opening the webview triggers it on my device.

OnePlus 5T
Android 9

**Comment by Jays2Kings** [comment] 2020-01-08 16:37
Closing this only because it is a duplicate of #39

**Closed by Jays2Kings** 2020-01-08 16:37 UTC
Labels: bug
