### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by laufeyss** [Jays2Kings/tachiyomiJ2K#1181] opened 2022-03-17 08:14 UTC
Top of the reader pops up while taking a long screenshot
![Screenshot_2022-03-17-16-11-17-20](https://user-images.githubusercontent.com/99605276/158765678-41af6db1-1acb-4f7e-9ac7-e88154abef93.jpg)

**Comment by Jays2Kings** [comment] 2022-04-15 20:34
dupe of https://github.com/Jays2Kings/tachiyomiJ2K/issues/977

**Closed by Jays2Kings** 2022-04-15 20:34 UTC
