### ISSUE TITLE
Extended toolbar creates a bug with the category list. 

### ISSUE THREAD

**Issue by Syzygos** [Jays2Kings/tachiyomiJ2K#1244] opened 2022-05-06 05:58 UTC
### Steps to reproduce

1. First off all 'show all categories' must be unchecked from settings → library → display options → categories tab.
2. Enable the extended toolbar option from settings → appearance. 
3. On your library screen, click on the category name to bring up your list of categories. 
4. Only the last category from the list is shown.
5. Tap on the category to switch to it and try changing categories again. You will see that now all of them are shown. 
6. Switch back to the first category on the list and now the last one is only visible again. 

### Expected behavior

It should display all categories from your list when clicking on the category name like in the image below. 

![Screenshot_20220505-215205_TachiyomiJ2K_1](https://user-images.githubusercontent.com/9330669/167071230-90bfbeb3-a4de-4195-8529-5f439d7b4d95.png)

### Actual behavior

Only the last category on the list is shown when trying to switch categories. If I switch to that category it'll then display them all like in the image in the expected behavior section. 

![Screenshot_20220505-215226_TachiyomiJ2K](https://user-images.githubusercontent.com/9330669/167074171-39e461c3-924b-4708-8dc3-226ee7ad215e.png)

This seems to be random because when I tested this on a fresh install with the same exact settings and same amount of categories I was only seeing the current category on the list and wasn't able to switch categories at all. When I tried it with  2 - 4 categories nothing showed up on the list at all.

### TachiyomiJ2K version

1.5.0

### Android version

Android 12

### Device

Device: Samsung Galaxy Tab S6, Model: SM-T860

### Other details

I was able to circumvent this issue by either enabling the option to show all categories or by using the category hopper so it's not that huge of an issue! 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Tachiyomi](https://github.com/tachiyomiorg/tachiyomi)
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[1.5.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by Jays2Kings** [comment] 2022-05-06 17:56
Dupe of https://github.com/Jays2Kings/tachiyomiJ2K/issues/1224

**Closed by Jays2Kings** 2022-05-06 17:56 UTC
Labels: bug
