### ISSUE TITLE
[Feature Request] Zip Support

### ISSUE THREAD

**Issue by Addicted5** [Jays2Kings/tachiyomiJ2K#84] opened 2020-01-29 08:58 UTC
There has been already a request to compress images while downloading to save disk space.
It would be also nice to store images in zip file while downloading.

**Comment by Jays2Kings** [comment] 2020-01-30 03:03
The request doesn't mention anything about compressing, just general "data saving" so this is still a duplicate of the request before

**Closed by Jays2Kings** 2020-01-30 03:03 UTC
Labels: enhancement
