### ISSUE TITLE
Coloured Header appears while reading manga

### ISSUE THREAD

**Issue by vanessabluellie** [Jays2Kings/tachiyomiJ2K#338] opened 2020-05-06 06:49 UTC
**App version:** tachiyomij2k-1.0.0

**Android version:** 8.0

**Issue/Request:** a coloured header (depending on theme chosen for app) appears when reading manga and won't disappear

**Steps to reproduce (if applicable)**

 1. In history or favourites, click a chapter to read, all is okay and there is no transparent coloured header yet that overlaps the pages at the top.
 2. But if the reader wants to change the settings, then they click on the page to do so
 3. Then they click again and then the header stays there until you click out of the manga. 

**Other details:** I'm not very good at explaining, but here is a screenshot!

![20200506_161855](https://user-images.githubusercontent.com/55352222/81145377-51a76980-8fb5-11ea-8cfa-3e25437b6350.jpg)

**Comment by CarlosEsco** [comment] 2020-05-06 12:47
please update to 1.0.2.

**Comment by Jays2Kings** [comment] 2020-05-06 21:01
Bug exists in 1.0.2 but is is a duplicate of #314

**Closed by Jays2Kings** 2020-05-06 21:01 UTC
