### ISSUE TITLE
[Feature Request] Badges inside of manga image

### ISSUE THREAD

**Issue by KraXen72** [Jays2Kings/tachiyomiJ2K#945] opened 2021-07-24 19:20 UTC
## Why/User Benefit/User Problem
currently, download and new badges are outside of the manga image. this feels quite wierd and it would be better to have them in the manga image like main tachiyomi has. 

### What/Requirements
im all for full border-radius (so they look like a pill) but please put them in the bounds of the manga image

**Comment by Jays2Kings** [comment] 2021-07-24 22:41
Duplicate of #821, #238

**Closed by Jays2Kings** 2021-07-24 22:41 UTC
Labels: feature
