### ISSUE TITLE
[Bug] Some Manga Chapters Didn't Load 

### ISSUE THREAD

**Issue by ShuriKim** [Jays2Kings/tachiyomiJ2K#884] opened 2021-07-02 20:38 UTC
### Device information
* Tachiyomi version : 1.0.17
* Android phone & version: Samsung A30 / SM-A305F / Android 11

## Steps to reproduce
1. Open app
2. Check some manga chapters

### Expected behavior
Manga load just fine

### Actual behavior
Some chapter failed to load as if my phone dont have connection but the connection is fine

### Other details
Some manga got duplicates chapters and unreadable due to the same problem

**Comment by DaviDeMeo** [comment] 2021-07-02 22:00
Is this reproducible in Tachiyomi or just in TachiyomiJ2K?
If both have this behavior it may be a problem with the extension and you should create an issue [here](https://github.com/tachiyomiorg/tachiyomi-extensions)

**Comment by Jays2Kings** [comment] 2021-07-03 01:28
Closing because issue rules weren't read

**Closed by Jays2Kings** 2021-07-03 01:28 UTC
Labels: bug
