### ISSUE TITLE
[Bug] Crash when opening display settings

### ISSUE THREAD

**Issue by mediocre123** [Jays2Kings/tachiyomiJ2K#711] opened 2021-04-02 22:57 UTC
### Device information
* Tachiyomi version: J2K 1.0.11
* Android phone & version: Galaxy Tab S6 running Android 11

## Steps to reproduce
1. Open any chapter in Reader view
2. Tap the "Display settings" icon in the top right, to the left of the three dots

### Expected behavior
Display settings should open, which allow things like configuration of an individual manga/comic's scrolling direction

### Actual behavior
Tachiyomi J2K crashes and reopens to the library

### Other details
Problem does not occur on a Pixel 4a running Android 11 and the latest version of J2K. Problem does not occur in the latest release of Tachiyomi stable.
Log file attached
[J2K crash.txt](https://github.com/Jays2Kings/tachiyomiJ2K/files/6251508/J2K.crash.txt)

**Comment by Jays2Kings** [comment] 2021-04-07 04:42
Dupe of #697 see it for the workaround

**Closed by Jays2Kings** 2021-04-07 04:42 UTC
Labels: bug
