### ISSUE TITLE
Text becomes difficult to read; whole UI gets buggy

### ISSUE THREAD

**Issue by RangaxRanga** [Jays2Kings/tachiyomiJ2K#39] opened 2020-01-07 16:20 UTC
### Device information
* Tachiyomi version: 0.9.56
* Android version: OxygenOS 9.0.6

## Steps to reproduce
1. First step: turn the app theme to "dark theme"
2. Second step: open "Catalogues"
3. Third step: Search for any manga
4. fourth step: While the results are still loading, select a already loaded manga.
### Expected behavior
You should see the text normally without any difficulty.

### Actual behavior
The whole screen looks like an black screen which is transparent to a certain degree, so you can still read the normal text, if you try to.

### Other details
When the glitch happened in the "Catalogues" tab, the text from my library gets also glitchy. Not only does the text become difficult to read, even the black/ dark background of my library/ the background of the episode list from every manga turns suddenly white, also the background of the "Catalogues" tab.
![grafik](https://user-images.githubusercontent.com/59615950/71910234-dbfbd000-3171-11ea-9678-ffd01dcc2274.png)
![grafik](https://user-images.githubusercontent.com/59615950/71910290-e9b15580-3171-11ea-8838-9e966bf70017.png)
![grafik](https://user-images.githubusercontent.com/59615950/71910301-ecac4600-3171-11ea-9d22-d0b444926de2.png)

**Comment by Jays2Kings** [comment] 2020-01-08 02:51
Can you tell me if other apps that have native dark modes (such as google keep, official reddit app, google play store)? I'm unable to reproduce this on all the devices I have, and I'm seeing some things on oneplus forums about bugs similar to this on official apps

**Comment by arkon** [comment] 2020-01-08 04:11
This happened once for me, also on an OnePlus device. Haven't had issues in other apps.

**Comment by Jays2Kings** [comment] 2020-01-08 04:57
I don't have a oneplus device to test but I've seen that it oxygen 9 could be a bit busted with dark themes.

Some examples:
https://forums.oneplus.com/threads/dark-theme-bug.991036/
https://forums.oneplus.com/threads/dark-theme-problem.990967/
https://forums.oneplus.com/threads/dark-theme-bug-in-contact.944990/

I'm not sure if there's a fix from my end without reverting how the themes work in this fork

**Comment by Jays2Kings** [comment] 2020-01-08 16:38
Ok I may have spoke too soon, there might be a fix for this, but I can't test it. I will comment on this issue again once a release contains a fix

**Comment by Jays2Kings** [comment] 2020-01-09 09:10
This bug _should_ be fixed now as of 0.9.6. I'll close this out once it is confirmed fixed by others

**Comment by RangaxRanga** [comment] 2020-01-09 16:41
I can still create the Bug, even with the new version. I only use darkmode with twitter and Tachyomi, no other apps. But the original Tachyomi (not j2k fork) had never this bug happened. But I also had only 2 sources, so it never loaded that long).

**Comment by Jays2Kings** [comment] 2020-01-10 16:22
Closing as @RangaxRanga has confirmed the bug is fixed with 0.9.61

**Closed by Jays2Kings** 2020-01-10 16:22 UTC
Labels: bug
