### ISSUE TITLE
[Feature Request] Load Next Chapter Ahead of Time

### ISSUE THREAD

**Issue by rl559** [Jays2Kings/tachiyomiJ2K#143] opened 2020-03-12 20:07 UTC
### Why/User Benefit/User Problem
This would make transitioning from chapter to chapter a much easier experience, especially when users may have spotty internet signal.

### What/Requirements
If the current chapter is done loading, begin loading the next chapter. This option could also be turned on/off in settings or only allowed under certain conditions such as "WiFi Only" or "Only While Charging".

**Comment by arkon** [comment] 2020-03-12 21:08
It already does. It does so on the last page in stable and within the last 3 pages in dev.

**Comment by joseph619** [comment] 2020-03-12 21:32
Duplicate of #80

**Closed** 2020-03-13 15:23 UTC
