### ISSUE TITLE
[Bug] Locking unwanted behaviour

### ISSUE THREAD

**Issue by Zero992** [Jays2Kings/tachiyomiJ2K#1007] opened 2021-09-23 09:33 UTC
### Device information
* Tachiyomi version: v.1.3.1
* Android phone & version: Xiaomi Redmi Note 9 Pro, version MIUI Global 12.0.4, Android 11 RKQ1.200826.002

## Steps to reproduce
1. Setting->Security->Lock with biometrics ON must be on
2. Locking and unlocking phone, fast so it doesn't ask for biometrics upon its return to app.
2. Go to Recents

### Expected behavior
Able to see change selected library save location, download chapters and see read status of them

### Actual behavior
Selected manga with have its Library section locked and with not show chapter read status and if any is downloaded.

**Comment by Jays2Kings** [comment] 2021-10-17 23:04
I'm closing this because this is an edge case for miui phones. I cannot reproduce this on other devices. I also don't see how this is an issue since you still need biometrics to unlock your phone again in the first place.

**Closed by Jays2Kings** 2021-10-17 23:04 UTC
Labels: bug
