### ISSUE TITLE
[Feature Request] An option to delete downloaded chapters

### ISSUE THREAD

**Issue by Rubberxgum** [Jays2Kings/tachiyomiJ2K#1029] opened 2021-10-09 06:05 UTC
### Why/User Benefit/User Problem
It can help to save storage.

### What/Requirements
Add an option to delete downloaded chapters from a manga after long pressing it. This feature is already on the Tachiyomi stable ver. btw.

![IMG_20211009_140458.jpg](https://user-images.githubusercontent.com/90501519/136646233-fe6e7ebe-eed3-40e3-af07-9394e5264e18.jpg)

**Comment by Caio99BR** [comment] 2021-10-18 05:12
> Isn't this feature already available? You just have to do it per manga at the moment using the 3dot menu. Or you delete all downloaded chapters through the settings

This delete all the downloaded chapters, regardless of whether it has already been read or not

Related commits:
https://github.com/tachiyomiorg/tachiyomi/commit/458e761b458bb3cb41924e88643faf2ee7efd4d9#diff-0b095016891d4803bf45a3562cebb5ad29b6c3cbaa1baa94dcbc7f90356ba778
https://github.com/tachiyomiorg/tachiyomi/commit/8362bf0886d5c12e2a588895d470098fedf68529#diff-0b095016891d4803bf45a3562cebb5ad29b6c3cbaa1baa94dcbc7f90356ba778

**Comment by Caio99BR** [comment] 2022-04-23 01:21
@Jays2Kings related issues #121 and maybe #59

**Comment by Jays2Kings** [comment] 2022-04-23 03:07
This is a dupe of #121

**Closed by Jays2Kings** 2022-04-23 03:07 UTC
Labels: feature
