### ISSUE TITLE
[Bug] App Crash with v1.3.0

### ISSUE THREAD

**Issue by haorh** [Jays2Kings/tachiyomiJ2K#996] opened 2021-09-14 15:26 UTC
### Device information
* Tachiyomi version: v1.3.0
* Android phone & version: Huawei P9 plus Android 7.0

## Steps to reproduce
1. Open app
2. It kill itself

### Expected behavior
Don't crash

### Actual behavior
Crashed. It happens a few days after i updated to v1.3.0. It was working fine before.

### Other details
```
09-14 23:15:36.984  1198  1220 I ActivityManager: Displayed eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.main.MainActivity: 0 (total +2s148ms)
09-14 23:15:37.082  1198  2512 E HsmCoreServiceImpl: onTransact in code is: 103
09-14 23:15:37.082  1198  2512 I MediaProcessHandler: playingUids:
09-14 23:15:37.100 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101056c
09-14 23:15:37.100 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 23:15:37.100 15233 15233 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 23:15:37.100 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101062c
09-14 23:15:37.100 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101062d
09-14 23:15:37.100 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101062e
09-14 23:15:37.110 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101056c
09-14 23:15:37.110 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101058c
09-14 23:15:37.110 15233 15233 E ResourceType: Style contains key with bad entry: 0x01010605
09-14 23:15:37.110 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101062c
09-14 23:15:37.110   573   573 I fingerprintd: FingerprintDaemonProxyEx::onTransact, code:1002
09-14 23:15:37.110 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101062d
09-14 23:15:37.110 15233 15233 E ResourceType: Style contains key with bad entry: 0x0101062e
09-14 23:15:37.110   573   573 I fingerprintd: set-liveness_switch
09-14 23:15:37.110   573   573 I fingerprintd: FingerprintDaemonProxyEx::setLivenessSwitch
09-14 23:15:37.110   573   573 I fingerprintd: fingerprintdex--dev->need_liveness_authentication = false;
09-14 23:15:37.110   573   573 I fingerprintd: FingerprintDaemonProxyEx::onTransact, code:7
09-14 23:15:37.111   573  1339 I fpc_fingerprint_hal: wait_finger_down: operation cancled
09-14 23:15:37.114 15233 15233 W ResourceType: Invalid package identifier when getting bag for resource number 0x00000279
09-14 23:15:37.120   573   573 I fingerprintd: FingerprintDaemonProxyEx::onTransact, code:1
09-14 23:15:37.128   573  1339 I fpc_tac : fpc_tac_send_get_indices_cmd indices:0x7e2e02a320, index_count:3
09-14 23:15:37.129   573  1339 E fpc_tac : fpc_tac_begin_identify---need_liveness_authentication: 0
09-14 23:15:37.138   573  1339 I fpc_tac : fpc_tac_send_set_arbitrary_data_cmd:ok, response:0
09-14 23:15:37.150 15233 15233 E ACRA    : ACRA caught a RuntimeException for eu.kanade.tachiyomi.j2k
09-14 23:15:37.150 15233 15233 E ACRA    : java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.kanade.tachiyomi.j2k/eu.kanade.tachiyomi.ui.security.BiometricActivity}: android.view.InflateException: Binary XML file line #39: Binary XML file line #39: Error inflating class <unknown>
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.os.Handler.dispatchMessage(Handler.java:105)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.os.Looper.loop(Looper.java:156)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.main(ActivityThread.java:6523)
09-14 23:15:37.150 15233 15233 E ACRA    :      at java.lang.reflect.Method.invoke(Native Method)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
09-14 23:15:37.150 15233 15233 E ACRA    : Caused by: android.view.InflateException: Binary XML file line #39: Binary XML file line #39: Error inflating class <unknown>
09-14 23:15:37.150 15233 15233 E ACRA    : Caused by: android.view.InflateException: Binary XML file line #39: Error inflating class <unknown>
09-14 23:15:37.150 15233 15233 E ACRA    : Caused by: java.lang.reflect.InvocationTargetException
09-14 23:15:37.150 15233 15233 E ACRA    :      at java.lang.reflect.Constructor.newInstance0(Native Method)
09-14 23:15:37.150 15233 15233 E ACRA    :      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.createView(LayoutInflater.java:656)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:711)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:59)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:728)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:796)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.Dialog.dispatchOnCreate(Dialog.java:524)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.Dialog.show(Dialog.java:385)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:687)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.Activity.performStart(Activity.java:6935)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.os.Handler.dispatchMessage(Handler.java:105)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.os.Looper.loop(Looper.java:156)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.main(ActivityThread.java:6523)
09-14 23:15:37.150 15233 15233 E ACRA    :      at java.lang.reflect.Method.invoke(Native Method)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
09-14 23:15:37.150 15233 15233 E ACRA    : Caused by: android.content.res.Resources$NotFoundException: Drawable eu.kanade.tachiyomi.j2k:color/secondary_highlight with resource ID #0x7f060237
09-14 23:15:37.150 15233 15233 E ACRA    : Caused by: android.content.res.Resources$NotFoundException: File res/color/secondary_highlight.xml from drawable resource ID #0x7f060237
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:935)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:769)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.content.res.Resources.loadDrawable(Resources.java:921)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.content.res.TypedArray.getDrawable(TypedArray.java:983)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.View.<init>(View.java:4193)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.View.<init>(View.java:4100)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.View.<init>(View.java:4079)
09-14 23:15:37.150 15233 15233 E ACRA    :      at java.lang.reflect.Constructor.newInstance0(Native Method)
09-14 23:15:37.150 15233 15233 E ACRA    :      at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.createView(LayoutInflater.java:656)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:711)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:59)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.policy.HwPhoneLayoutInflater.onCreateView(HwPhoneLayoutInflater.java:107)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.onCreateView(LayoutInflater.java:728)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:796)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.rInflate(LayoutInflater.java:872)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.Dialog.dispatchOnCreate(Dialog.java:524)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.Dialog.show(Dialog.java:385)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:687)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
09-14 23:15:37.150 15233 15233 E ACRA    :      at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.Activity.performStart(Activity.java:6935)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.os.Handler.dispatchMessage(Handler.java:105)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.os.Looper.loop(Looper.java:156)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.app.ActivityThread.main(ActivityThread.java:6523)
09-14 23:15:37.150 15233 15233 E ACRA    :      at java.lang.reflect.Method.invoke(Native Method)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
09-14 23:15:37.150 15233 15233 E ACRA    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
09-14 23:15:37.150 15233 15233 E ACRA    : Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #3: <item> tag requires a 'drawable' attribute or child tag defining a drawable
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:183)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:116)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:133)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1224)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1197)
09-14 23:15:37.150 15233 15233 E ACRA    :      at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:925)
09-14 23:15:37.150 15233 15233 E ACRA    :      ... 51 more
09-14 23:15:37.152 15233 15329 I System.out: [dumpsys, meminfo, 15233]
09-14 23:15:37.152 15233 15329 I System.out: null
09-14 23:15:37.152 15233 15329 I System.out: null
09-14 23:15:37.154 15233 15329 I System.out: Calling by::className:org.acra.collector.MemoryInfoCollector  MethodName:collectMemInfo
09-14 23:15:37.160 15233 15336 W ACRA    :
09-14 23:15:37.160 15233 15336 W ACRA    : org.acra.collector.CollectorException: Error while retrieving BUILD_CONFIG data:eu.kanade.tachiyomi.j2k.BuildConfig
09-14 23:15:37.160 15233 15336 W ACRA    :      at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:60)
09-14 23:15:37.160 15233 15336 W ACRA    :      at org.acra.data.CrashReportDataFactory$createCrashData$$inlined$map$lambda$1.run(CrashReportDataFactory.kt:58)
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.lang.Thread.run(Thread.java:776)
09-14 23:15:37.160 15233 15336 W ACRA    : Caused by: java.lang.ClassNotFoundException: eu.kanade.tachiyomi.j2k.BuildConfig
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.lang.Class.classForName(Native Method)
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.lang.Class.forName(Class.java:400)
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.lang.Class.forName(Class.java:326)
09-14 23:15:37.160 15233 15336 W ACRA    :      at org.acra.collector.ReflectionCollector.getBuildConfigClass(ReflectionCollector.kt:96)
09-14 23:15:37.160 15233 15336 W ACRA    :      at org.acra.collector.ReflectionCollector.collect(ReflectionCollector.kt:50)
09-14 23:15:37.160 15233 15336 W ACRA    :      at org.acra.collector.BaseReportFieldCollector.collect(BaseReportFieldCollector.kt:56)
09-14 23:15:37.160 15233 15336 W ACRA    :      ... 6 more
09-14 23:15:37.160 15233 15336 W ACRA    : Caused by: java.lang.ClassNotFoundException: Didn't find class "eu.kanade.tachiyomi.j2k.BuildConfig" on path: DexPathList[[zip file "/data/app/eu.kanade.tachiyomi.j2k-1/base.apk"],nativeLibraryDirectories=[/data/app/eu.kanade.tachiyomi.j2k-1/lib/arm64, /data/app/eu.kanade.tachiyomi.j2k-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
09-14 23:15:37.160 15233 15336 W ACRA    :      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
09-14 23:15:37.160 15233 15336 W ACRA    :      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-14 23:15:37.160 15233 15336 W ACRA    :      ... 12 more

```

**Comment by Jays2Kings** [comment] 2021-09-14 21:22
Dupe of https://github.com/Jays2Kings/tachiyomiJ2K/issues/994

Fix coming soon

**Closed by Jays2Kings** 2021-09-14 21:22 UTC
Labels: bug
