### ISSUE TITLE
[Bug] Write short description here

### ISSUE THREAD

**Issue by Saumyavilasroy** [Jays2Kings/tachiyomiJ2K#44] opened 2020-01-09 06:24 UTC
### Device information
* Tachiyomi version: 0.9.56
* Android version:8
![Screenshot_20200109-115046](https://user-images.githubusercontent.com/59217434/72043241-ab817680-32d6-11ea-9fad-56fcc75b3000.jpg)
![Screenshot_20200109-115101](https://user-images.githubusercontent.com/59217434/72043244-ab817680-32d6-11ea-8b54-f4407a15785a.jpg)

**Comment by Jays2Kings** [comment] 2020-01-09 07:24
duplicate of #39 and next time please provide more information about how to reproduce this as well as a meaningful title

**Closed by Jays2Kings** 2020-01-09 07:24 UTC
Labels: bug
