### ISSUE TITLE
[Bug] hide filter

### ISSUE THREAD

**Issue by amboris** [Jays2Kings/tachiyomiJ2K#400] opened 2020-05-12 18:41 UTC
Hide filder setting option doesnt work. I dont even know why filter bar is a thing to have enabled as preset. 99% of people set it up once and leave it as it is. It just take space with potencial risk for accidential use.

**Comment by Jays2Kings** [comment] 2020-05-23 08:15
Because it's to let users know the the filter bar is there. It also shows up the first time on load regardless of the setting because you have a filter enabled, because 99% of people don't set it up once and leave it as it is. If that was the case, stable wouldn't have the yellow tint on the filters to show that they are enabled. 

It still shows because users toggle them on and off either constantly or every so often, so it shows so users know they're still on. It also still hides when you scroll it away

**Comment by amboris** [comment] 2020-05-23 09:10
In the original ui design it was an easy popup menue that didnt border as it was not present all the time. This filter bar feels to me like an unessesary ad-banner that i click away the first thing when i open the app.

"Because it's to let users know the the filter bar is there."
I dont think its needed after you find the setting hide bar at startup. You allready know its there and where to find it. So as standard preset to get user get used to the new ui its ok. But as soon as you get comfortable with the new ui its starts to border as user want to optimize the ui to their liking and know the standard behaviours and where to find what. For me its just thightens up space unessesary. As for practical usecase as of now, every time i open the app the first thing i do is to close the filter bar with only one filter enabled "show unread only" thats really the only filter i use. And maybe i toggle it off some times to search my lib. So every time i open the app i have to do one unessesary step after opening the app. Its feels like doing the opening app steps twice compared to the old ui every time.

I honestly can not imagine that there are more masses that want the filterbar visible as preset than have it hidden with some set filter on. as surely these people do not change filter setting every time they open the app As in the other hand, people who dont mess much with filter just want to see their unread mangas without additional menues. Its like opening an pdf editor with all the toolmenue when all you want is just read the pdf files and for that a simple plain pdf reader would do.

**Comment by CarlosEsco** [comment] 2020-05-23 22:18
Closing since this is as designed

**Closed by CarlosEsco** 2020-05-23 22:18 UTC
Labels: bug
