### ISSUE TITLE
[Feature Request] Migrate bookmarks

### ISSUE THREAD

**Issue by James-Yuji** [Jays2Kings/tachiyomiJ2K#671] opened 2021-03-12 04:33 UTC
Why/User Benefit/User Problem
(when migrating a manga/manhwa/webtoon there is no option to migrate bookmarks, hence whenever a title is migrated, all bookmarks are deleted)

What/Requirements
(A option in the migrating menu with such feature would help, put it beside the "tracking" "chapters" "categories" as a data to choose to migrate with the title)

**Comment by GreatestFool** [comment] 2021-04-07 12:57
Considering the naming conventions between sources, perhaps merely having a config option to enable manual transfer could be a decent solution? For example, it lists the chapters the original has bookmarked and makes suggestions for the new source, and if it is not right, the end user can simply edit it and fix it before the migration.

**Comment by joseph619** [comment] 2021-04-13 14:33
Duplicate of #151

**Closed** 2021-04-13 14:34 UTC
Labels: feature
