### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by ramma1** [Jays2Kings/tachiyomiJ2K#258] opened 2020-05-02 00:40 UTC
1.0.1

Android 9

Issue

**Steps to reproduce (if applicable)**

 1. Open Library
 2. It crashes
 3.

Downloaded the new version (first 1.0.0 and then 1.0.1, both had the issue) and it was working fine  but now when ever I open to home page (library) , the app crashes. If I open the app to extensions or updates by long pressing the icon, it open the app but if I click on library it crashes again. Thanks

**Comment by Jays2Kings** [comment] 2020-05-02 01:04
Please provide what phone you have as well

**Comment by ramma1** [comment] 2020-05-02 01:58
S8+

**Comment by SurReal223** [comment] 2020-05-02 04:58
I haven't faced any crashes on the Library page, but I am crashing consistently after I reach the end of a chapter. I think it has something to do with updating tracking since I've also crashed when I went to update my current chapter with Anilist.

Pixel 2 XL
1.0.1
Android 10

**Comment by CarlosEsco** [comment] 2020-05-02 13:31
can you relogin to your trackers

**Comment by SurReal223** [comment] 2020-05-02 13:59
I made sure to attempt to relog into both trackers on 1st reinstall, but I was unable to also relog into Kitsu due to the site returning 502 errors. Anilist logged in like normal. It was working normal at first, but soon would start force closing again as you can see by the multiple edits to my previous comment when I originally thought the problem fixed itself on reinstall. 

However, I've reinstalled it for a 3rd time, logged into Anilist, and have not been able to reproduce the crash again no matter what I try (reading a new chapter in a tracked manga, reading a new chapter in an untracked manga, reading a chapter that previously crashed on complete before, and reading a chapter that had not crashed before) so I'm even less unsure of what could be causing the issue at this point. All I know is that at some point for whatever reason, a crash will occur after reading a chapter (It seems to happen on the final page, not the chapter transistion screen) that will require a force-stop of the app in order to reopen it, and the chapter will say it's unread (Attempting to re-read it again will crash it again).

**Comment by ramma1** [comment] 2020-05-02 20:06
It seems that after updating my tracking and re-installing the app, it has been fixed. I have yet to have the same problem again.

**Closed** 2020-05-03 01:43 UTC
