### ISSUE TITLE
[Bug] Categories unable to reorganize

### ISSUE THREAD

**Issue by SunBreaker1** [Jays2Kings/tachiyomiJ2K#969] opened 2021-08-12 16:52 UTC
### Device information
* Tachiyomi version: 1.2.1
* Android phone & version: S10e Android 11

## Steps to reproduce
1. Create a category
2. Try and move it down the list

### Expected behavior
The category should be able to be moved and stay in its position

### Actual behavior
The category once it reaches a certain position down the list, the app "freaks out" and resets the position of the category.

https://user-images.githubusercontent.com/85519676/129236458-ad5166a9-a7b8-4ff3-9609-be32bb8b43f2.mp4

### Other details
I have a lot of categories, so this might not be an issue with less categories

**Comment by Jays2Kings** [comment] 2021-08-14 19:47
Duplicate of #898

**Closed by Jays2Kings** 2021-08-14 19:47 UTC
Labels: bug
