### ISSUE TITLE
[Feature Request] Modify the automated search suggestions

### ISSUE THREAD

**Issue by dashnak** [Jays2Kings/tachiyomiJ2K#883] opened 2021-07-02 04:15 UTC
The search suggestions in the search bar are randomized and, on several occasions, really inappropriate. The search bar suggests things like "rape" and "anal" along normal terms like "isekai" or "shounen". 

### Why/User Benefit/User Problem
Regardless of whether the user installs and browses +18 extensions like NHentai, it's probably not a good idea for those search suggestions to appear. If somebody wants to read stuff like that, they'll search for it. No need to suggest it. It can cause problems for the users. 

### What/Requirements
Simply show ONLY neutral suggestions in the search bar.

**Comment by DaviDeMeo** [comment] 2021-07-02 11:29
Duplicate of #856

**Comment by dashnak** [comment] 2021-07-02 13:17
Don't think it's the same. #856 was dismissed according to the content of the mangas themselves. I'm not suggesting we reclassify or pass judgment on the content of a specific manga. I'm talking about words only. Words like "anal", "incest" or "loli" that show up as suggestions in the general search bar are clearly a problem if one does not want it to be assumed that one is reading adult material on their phone (regardless of whether they do or not, that's clearly not the issue here).

**Comment by fleurc** [comment] 2021-07-02 13:24
Agreeing with this issue. While there is a way to disable suggestions entirely there is no such feature to disable NSFW specific suggestions.

This has been a reported issue i've seen a few times here, it should most likely be addressed as something to enable or disable. Possibly through another option stating "Show only Neutral suggestions" or "Show all suggestions" maybe worded differently as to clearly state the intent of the feature.

**Comment by arkon** [comment] 2021-07-02 13:25
Definitely a duplicate of #856. If the tags come from NSFW manga, why would this not be the same thing?

**Comment by fleurc** [comment] 2021-07-02 13:32
@arkon pointed out what i fear may be the problem. This is not exclusively about the words, but that tachiyomi takes its suggested tags from the manga already in the library. Thus, unless provided a proof that it doesn't function this way, the issue will fall in that category and most likely should be referenced as a duplicate.

**Comment by dashnak** [comment] 2021-07-02 19:12
I don't know about the "already in the library part". I don't use any +18 extensions and I don't have any hentai saved in the library. I get why stuff like "harem" or "eechi" are not (and shouldn't be) a problem, they're not NSFW, but there's nothing in my library is tagged as "incest" or "rape". Seems to me the search term suggestions might come from somewhere else.

**Comment by DaviDeMeo** [comment] 2021-07-02 21:44
The suggestion get generated in this [function](https://github.com/Jays2Kings/tachiyomiJ2K/blob/050213a4a3c663e01be8051b6effaf0eb8dce2e3/app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt#L1053) from manga in your library or recently read manga.
The only possible suggestions are: 
1. source name (E.g.: "Mangabub", "ReadM", ...)
2. manga title (E.g.: "Onepuch-man", "SpyXFamily", ...)
3. tags from your recently read (E.g.: "action", "comedy", ...)

Maybe an extension is incorrectly flagged or tags for a manga are wrong, but suggestion don't come from "somewhere else".

The only NSFW settings that we have is to hide extension/source tagged as such. We could move those settings to a new section 
(called Adult or something similar) and add the option to hide manga from NSFW source in library and recent.

**Comment by fleurc** [comment] 2021-07-02 22:20
That'd be the best possible scenario, i feel that may solve the issues people have with search suggestion, while also may make the app more secure for minors who may not know or the like (Tho of course if they know what they're doing there ain't stopping them from finding such a thing). This will most likely optimize the use for some imo.

**Comment by dashnak** [comment] 2021-07-02 22:44
Seems like a nice solution.

**Comment by Jays2Kings** [comment] 2021-07-03 01:30
Basically a duplicate so closing

**Closed by Jays2Kings** 2021-07-03 01:30 UTC
Labels: feature
