### ISSUE TITLE
[Feature Request] Add thumbnails of pages

### ISSUE THREAD

**Issue by ShiSix** [Jays2Kings/tachiyomiJ2K#1245] opened 2022-05-06 09:39 UTC
### Describe your suggested feature

Its thumnail for all page in a chapter like this
![Screenshot_20220505-161750_Kotatsu](https://user-images.githubusercontent.com/101547113/167106763-a6b1a702-93e2-432f-8547-102bccfaf6fd.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an request for a feature in the original Tachiyomi, I am opening because multiple versions of TachiyomiJ2K have been released without this feature.
- [X] If this is an issue with an extension, or a request for an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[1.5.0](https://github.com/Jays2Kings/tachiyomiJ2K/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.

**Comment by Jays2Kings** [comment] 2022-05-06 17:55
Dupe of https://github.com/Jays2Kings/tachiyomiJ2K/issues/564

**Closed by Jays2Kings** 2022-05-06 17:55 UTC
Labels: feature
