### ISSUE TITLE
[Feature Request] option to change manga quality

### ISSUE THREAD

**Issue by axel05869** [Jays2Kings/tachiyomiJ2K#216] opened 2020-04-25 13:31 UTC
### Why/User Benefit/User Problem
(It will help the readers who have a slow internet connection to save time from loading large/high quality manga)

**Comment by CarlosEsco** [comment] 2020-04-25 17:37
That's entirely depends on your extension. The app doesn't host any manga so only serves whatever quality the website has

**Comment by joseph619** [comment] 2020-04-25 17:43
Duplicate of #18

**Comment by Jays2Kings** [comment] 2020-04-26 02:22
Different from that one, this getting a lower quality image on download, not compressing after the fact, and as Carlos has said, this is something extensions have to handle not the app. You can make a request on the extensions repo, but if it doesn't exists already its because the site doesn't support lower quality image requests

**Closed by Jays2Kings** 2020-04-26 02:22 UTC
Labels: feature
