### ISSUE TITLE
[Feature Request] Recent and History with Uniform Cover Option

### ISSUE THREAD

**Issue by iAmPhilo** [Jays2Kings/tachiyomiJ2K#947] opened 2021-07-24 21:56 UTC
### Why/User Benefit/User Problem
Just makes the app look more streamline and nicer as some covers have different sizes. This feature is on the Library tab but not on the Recents tab, some cover are not your standard and either very long, squared etc, which makes it look less nicer.

### What/Requirements
Should be similar or same as Uniform cover for Library tab.

**Comment by Jays2Kings** [comment] 2021-07-24 22:39
Duplicate of #384

**Closed by Jays2Kings** 2021-07-24 22:39 UTC
Labels: feature
