### ISSUE TITLE
[Feature Request] Exit tracking 

### ISSUE THREAD

**Issue by e-shl** [Jays2Kings/tachiyomiJ2K#340] opened 2020-05-06 11:56 UTC
### User Problem
The inability to exit the tracking service

### Requirements
Add menu/option  exit as in Tachiyomi
![2020-05-06 16-55-10](https://user-images.githubusercontent.com/35057681/81174024-7ce08780-8fba-11ea-9406-51d5989cafde.JPG)

**Comment by CarlosEsco** [comment] 2020-05-06 12:49
what do you mean?  pressing cancel exits the tracker does it not?

**Comment by CarlosEsco** [comment] 2020-05-06 12:50
jay this is only an issue for those that use OAuth so anilist and Shikimori.

**Comment by e-shl** [comment] 2020-06-03 18:20
@Jays2Kings ?

**Comment by CarlosEsco** [comment] 2020-06-03 19:39
I'm working on a pull request also in future don't ping people about status. It makes them less likely to want to do the feature

**Comment by Jays2Kings** [comment] 2020-06-04 01:52
If the issue isn't closed it means that it's still being considered. There's no reason to comment on every single request if there's nothing to add

 However if you want the feature asap, you're free to open a pull request yourself.

**Closed** 2020-06-06 23:53 UTC
Labels: feature
