### ISSUE TITLE
[Feature Request] set custom select chapters to mark read/unread chapters

### ISSUE THREAD

**Issue by FireNation323** [Jays2Kings/tachiyomiJ2K#774] opened 2021-04-30 08:46 UTC
### Why/User Benefit/User Problem
(explain why this feature should be added)
For example I want to mark chapter 60-100 as read but I want to keep chapter 1-60 I'll have to manually mark as read ch 60-100 which takes a long time and it sometimes glitches and you see green lines between chapters and sometimes the chapters don't get marked as read/unread and you have to swipe again

### What/Requirements
(explain how this feature would behave)
1-go to manga 
2- click and hold on the chapter almost like download but on the other side and it will give you the option to either mark as read or unread

**Comment by Jays2Kings** [comment] 2021-04-30 18:45
Duplicate of https://github.com/Jays2Kings/tachiyomiJ2K/issues/319

**Closed by Jays2Kings** 2021-04-30 18:45 UTC
Labels: feature
