### ISSUE TITLE
[Bug] App closes when I press update all extensions button,

### ISSUE THREAD

**Issue by iam-Ameena** [Jays2Kings/tachiyomiJ2K#1127] opened 2021-12-27 16:54 UTC
---

### Device information
* Tachiyomi version: 1.4.4
* Android phone & version: Redmi 5, Android 11

## Steps to reproduce
1. Open tachiyomi j2k
2. Go to extensions and press update all

### Expected behavior
It should update all the extensions

### Actual behavior
It just closes the app without showing any error and none of the extensions get updated.

### Other details
I can update the extensions normally.

**Comment by MindFlayeR57** [comment] 2021-12-27 21:18
Same here
(OnePlus 7T pro android 11)

**Comment by vipzzx** [comment] 2022-01-11 02:33
Same here. Note9 android 10

**Comment by Caio99BR** [comment] 2022-04-23 01:04
Duplicate of #918, and (maybe) already fixed on MIUI 12.8 or forks

**Comment by MindFlayeR57** [comment] 2022-04-23 01:14
> Duplicate of #918, and (maybe) already fixed on MIUI 12.8 or forks

Yes but not really. Here the app crashes completely, on #918 it just doesn't update the extensions.

**Comment by Caio99BR** [comment] 2022-04-23 01:24
@MindFlayeR57 you already tried on latest release?

**Comment by MindFlayeR57** [comment] 2022-04-23 01:27
@Caio99BR no, I don't have any extensions that need updating.

**Comment by Caio99BR** [comment] 2022-04-23 01:29
Try with this https://github.com/tachiyomiorg/tachiyomi-extensions/blob/94de2005cd175386c9ae602a7ae6b8a74ccd34e5/apk/tachiyomi-all.batoto-v1.2.21.apk

**Comment by Jays2Kings** [comment] 2022-04-23 01:33
Closing this anyway since it was a duplicate issue

**Closed by Jays2Kings** 2022-04-23 01:33 UTC
Labels: bug
