### ISSUE TITLE
[Bug] Some titels make top right dots disappear

### ISSUE THREAD

**Issue by ardittristan** [Jays2Kings/tachiyomiJ2K#79] opened 2020-01-22 02:25 UTC
### Device information
* Tachiyomi version: 9.7
* Android phone & version: 8

## Steps to reproduce
1. First step
Go to https://mangadex.org/manga/39728/
(have had it happen on different titles as well)
### Expected behavior
3 dots
![Screenshot_20200122-032409_Tachiyomi](https://user-images.githubusercontent.com/42787508/72860298-b8cf3580-3cc6-11ea-854a-bbe5b13b3b31.jpg)

### Actual behavior
No 3 dots
![Screenshot_20200122-031743_Tachiyomi](https://user-images.githubusercontent.com/42787508/72860198-6857d800-3cc6-11ea-876e-597f09d2f8ed.jpg)

### Other details
After i enable screen rotation, went to landscape mode and back it suddenly starts working.

**Comment by Jays2Kings** [comment] 2020-02-03 08:46
Since a few updates have happened since this was reported, can you confirm if this is still an issue?

**Comment by ardittristan** [comment] 2020-02-03 13:33
It seems to work now, before it was already kind of inconsistent so i can't be 100% sure

**Comment by Jays2Kings** [comment] 2020-02-16 03:57
Closing this then if it's no longer reproducible

**Closed by Jays2Kings** 2020-02-16 03:57 UTC
Labels: bug
