### ISSUE TITLE
[Feature Request] Search the all sources for the series

### ISSUE THREAD

**Issue by Hongsworth** [Jays2Kings/tachiyomiJ2K#296] opened 2020-05-03 00:43 UTC
### Why/User Benefit/User Problem
In the old version when tapping on a manga title it shows all the variant of the series on different sources, this allows us to see what source has the most updated version. I'm not sure if this feature is removed, if not could someone tell me to to do it.

### What/Requirements
When tapping on a title of the manga is shows a catalogue of the same manga but sperated by sources.

**Comment by CarlosEsco** [comment] 2020-05-03 12:31
Duplicate of another open issue

**Closed by CarlosEsco** 2020-05-03 12:31 UTC
Labels: feature

**Comment by Hongsworth** [comment] 2020-05-03 12:47
Could you link the issue please.

**Comment by CarlosEsco** [comment] 2020-05-03 13:29
sorry was on mobile.

#252

**Comment by Hongsworth** [comment] 2020-05-03 17:58
Thank you
